## TF Syntax Basics

In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

1.10.0


In [3]:
hello=tf.constant("hello")

In [4]:
world = tf.constant("world")

In [5]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [6]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [7]:
with tf.Session() as sess:
    result = sess.run(hello+world)

In [8]:
print(result)

b'helloworld'


In [9]:
a = tf.constant(10)

In [10]:
b = tf.constant(20)

In [11]:
a+b

<tf.Tensor 'add_1:0' shape=() dtype=int32>

In [12]:
with tf.Session() as sess:
    result = sess.run(a+b)

In [13]:
result

30

In [14]:
fill_mat = tf.fill((4,4),10)

In [15]:
zeros = tf.zeros((4,4))

In [16]:
ones = tf.ones((4,4))

In [17]:
randn = tf.random_normal((4,4),mean=0,stddev=1.0)

In [18]:
randu = tf.random_uniform((4,4),minval=0,maxval=1)

In [19]:
ops=[fill_mat,zeros,ones,randn,randu]

In [20]:
sess = tf.InteractiveSession()

In [21]:
for op in ops:
    print(sess.run(op))
    print('\n')

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[-1.0944338   0.8316684  -0.12732871 -0.4160004 ]
 [-0.8117378  -0.5054119  -0.9123163  -1.3697197 ]
 [-2.1832361  -0.02919791 -0.5771538  -0.2863671 ]
 [-0.6038277  -0.20475504 -1.3428915   0.88067776]]


[[0.108441   0.45812368 0.19335747 0.34923244]
 [0.6415442  0.52181816 0.9934696  0.0035758 ]
 [0.3830104  0.70425427 0.723969   0.90887785]
 [0.02236021 0.0741694  0.7750075  0.02909195]]


